import React from 'react';
import {Easing, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {COLORS, DISPLAY, Kicker, SceneShell} from './shared';

const outcomes=['Güçlü yön & değer haritası','90 günlük hedef planı','İletişim uygulama notu','Konuşma geri bildirimi','Zaman günlüğü','30 günlük eylem sözleşmesi'];

export const Outcomes:React.FC=()=>{
  const frame=useCurrentFrame(); const {fps,width,height}=useVideoConfig(); const portrait=height>width;
  return <SceneShell background={COLORS.ink} color={COLORS.white}><Kicker>Kişisel gelişim dosyası</Kicker><div style={{fontFamily:DISPLAY,fontSize:portrait?88:108,lineHeight:.9,letterSpacing:'-.055em',textTransform:'uppercase',maxWidth:1300,marginTop:24,opacity:interpolate(frame,[0,.65*fps],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),translate:interpolate(frame,[0,.75*fps],['0px 60px','0px 0px'],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)})}}>Altı haftanın sonunda<br/>elinde ne kalır?</div><div style={{display:'grid',gridTemplateColumns:portrait?'repeat(2,1fr)':'repeat(3,1fr)',gap:portrait?18:20,marginTop:portrait?70:55}}>{outcomes.map((text,index)=><div key={text} style={{minHeight:portrait?230:190,display:'flex',flexDirection:'column',justifyContent:'space-between',padding:portrait?28:30,borderRadius:22,color:index===5?COLORS.white:COLORS.ink,backgroundColor:index===5?COLORS.red:COLORS.bright,opacity:interpolate(frame,[index*.1*fps,(index*.1+.55)*fps],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),translate:interpolate(frame,[index*.1*fps,(index*.1+.65)*fps],[`0px ${80+index*7}px`,'0px 0px'],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)}),rotate:interpolate(frame,[index*.1*fps,(index*.1+.65)*fps],[`${index%2?-2:2}deg`,'0deg'],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}><b style={{fontSize:17,letterSpacing:'.14em',color:index===5?COLORS.white:COLORS.red}}>{String(index+1).padStart(2,'0')}</b><span style={{fontFamily:DISPLAY,fontSize:portrait?35:38,lineHeight:.98,letterSpacing:'-.035em',textTransform:'uppercase'}}>{text}</span></div>)}</div></SceneShell>;
};
